name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone directly to mounted path
        run: |
          cd /front
          git init
          git remote add origin "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/phoenix381/front.git"
          git fetch --prune
          git checkout -t origin/main

      - name: Restart front
        run: |
          docker restart vue_app