name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    # container:
      # image: ubuntu:latest
      # volumes:
        # - /front:/front
      # options: --mount type=bind,source=/front,target=/front
    steps:
      - name: Sync repo
        run: |
          # set dir as safe
            docker exec gitea_runner \
              git config --global --add safe.directory /front
          # Fetch repo
            docker exec gitea_runner \
              git -C /front pull "${{ secrets.TOKEN }}@projects.root.sx/phoenix381/front.git"
              # git -C /front fetch origin "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/phoenix381/front.git"
          # Execute git pull inside runner container
            docker exec gitea_runner \
              git -C /front reset --hard origin/main

          # pwd
          # ls -a /front
          # # ls -a /front/phoenix381

          # date >> date.txt

          # # Initialize repo if not exists
          # if [ ! -d "/front/.git" ]; then
          #   git -C /front init
          #   git -C /front remote add origin "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/phoenix381/front.git"
          # fi

          # git -C /front fetch origin
          # git -C /front reset --hard origin/main
          # git -C /front clean -fd

      - name: Restart front
        run: |
          docker restart vue_app