name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone directly to mounted path
        run: |
          cd /front
          git init
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          git fetch --prune
          git reset --hard "$GITHUB_SHA"
          git config --global --add safe.directory /front

      - name: Restart front
        run: |
          docker restart vue_app