name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone directly to mounted path
        run: |
          cd /front
          git pull
          # git init
          # git remote add origin "https://projects.root.sx/phoenix381/front.git"
          # git fetch --prune
          # git reset --hard "$GITHUB_SHA"
          # git config --global --add safe.directory /front

      - name: Restart front
        run: |
          docker restart vue_app