name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: /front

      - name: Restart front
        run: |
          docker restart vue_app