name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    container:
      image: ubuntu:latest
      volumes:
        - /front:${GITHUB_WORKSPACE}/workspace/front
    steps:
      - name: Clone directly to mounted path
        run: |
          ls -a /front

          # Initialize repo if not exists
          if [ ! -d "/front/.git" ]; then
            git -C /front init
            git -C /front remote add origin "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/phoenix381/front.git"
          fi

          git -C /front fetch origin
          git -C /front reset --hard origin/main
          git -C /front clean -fd

      - name: Restart front
        run: |
          docker restart vue_app