name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync repo
        run: |
          rsync -a --delete "$GITHUB_WORKSPACE/" /front/
          git -C /front config --global --add safe.directory /front

      - name: Restart front
        run: |
          docker restart vue_app